stages:
  - deploy
  - mirror

deploy:
  stage: deploy
  tags:
    - runner-development-shell
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - |
      sudo -u www rsync -az --no-o --no-g \
        --exclude=.git \
        --exclude=.env \
        --exclude=node_modules \
        --exclude=vendor \
        --exclude=storage \
        --exclude=proxy_cache_dir \
        --exclude=.user.ini \
        ./ "$DEPLOY_DIR/"

    - |
      sudo -u www bash -lc "
        cd '$DEPLOY_DIR'

        echo '=== NODE CHECK ==='
        which node
        node -v

        echo '=== NPM CHECK ==='
        which npm
        npm -v

        echo '=== COMPOSER INSTALL ==='
        composer install --no-interaction --prefer-dist --optimize-autoloader

        echo '=== NPM INSTALL ==='
        npm install

        echo '=== NPM BUILD ==='
        npm run build

        echo '=== MIGRATE ==='
        php artisan migrate --force

        echo '=== STORAGE LINK ==='
        php artisan storage:link
      "
